### ISSUE TITLE
Add JSDoc tags

### ISSUE THREAD

**Issue by daxtens** [daxtens/finvis#1]
2.5 hours ($100)

Read and understand the code enough to put [JSDoc 3](https://github.com/jsdoc3/jsdoc) tags on all undocumented functions/consts/variables/classes/etc.

While you're at it, make sure any thing that can have a [Closure type annotation](https://developers.google.com/closure/compiler/docs/js-for-compiler) has one. If/when appropriate, please @typedef classes (I'm thinking esp in parenting.js, viewobj.js and viewstate.js).

When you find something that's unclear, drop me a comment and I'll get back to you.

**Comment by axtens** [comment]
In parenting.js, line 9, is there a reason why you have 
    var _children = new Array();
rather than, say, 
    var _children = [];

**Comment by axtens** [comment]
In events.js there is the annotation
"    // ... is this necessary in the browsers we're supporting?"

What browsers are you supporting? Or is this more on the lines of http://www.quirksmode.org/js/events_properties.html in the "What is the type of the event?" part?

**Comment by daxtens** [comment]
Erm, IE 9+, and recent versions of FF, Safari, Chrome, Opera. (I haven't had to specify an exact version because they're all great at pushing their users to stay up to date.)

No reason off the top of my head for not using [].

**Comment by daxtens** [comment]
Sorry, forgot to reference this in b7261e2f0c. You're on the right track - just tighten up type annotations. Also the point of the add/remove methods is to hide the internal implementation details (and stop people monkeying around with the array except through the given methods), so don't tell people about the internals in the docstrings :)

**Comment by daxtens** [comment]
In hind sight, the doc string is now the name of the function, which also isn't great. Oh well - the functions are mostly self explanatory anyway.

**Comment by axtens** [comment]
Regarding events.js, what's the canonical way to mark up custom event handlers? I will ask around ...

**Comment by axtens** [comment]
http://stackoverflow.com/questions/2299891/new-with-jsdoc-best-way-to-document-an-event-handler-in-jsdoc but the answer is "no". Hmpf.

**Comment by axtens** [comment]
Some more helpful discussions here http://code.google.com/p/jsdoc-toolkit/issues/detail?id=78

**Comment by axtens** [comment]
Are you expecting documentation of jquery.contextmenu.r2.js. It's a third party file with a declaration within it saying, "For documentation visit http://www.trendskitchens.co.nz/jquery/contextmenu/". Have you tweaked this file at all?

**Comment by axtens** [comment]
``` javascript
/**
 * Move myself to the given position.
 * units are dollars
 * @param {Array.<number>} position New position.
*/
```

That's from viewobj.js. So where I've got {Position} you've got {Array.<number>}. That's still a bit ambiguous as a position had better be a two element array of numbers or things will fall over. How do you want to proceed with that? Specify that {Position} means {Array[0..1] of integer} (which is very Pascal)?

**Comment by axtens** [comment]
``` javascript
/**
 * canPopOut
 * @param {aggregate} aggregate Selected aggregate
 * @returns {integer} length of items of aggregate of data
 *  else length of items of data if there are items of data
 *  if there are no items in data, the result is undefined
 */
```

Notice that last line. Might be better to be more specific about the return value where there are no items.

**Comment by daxtens** [comment]
Okay:

Re events.js: I don't understand the `@event` tag either. Do whatever makes the most sense and generates the best output when run through jsdoc3. Also the docstrings need to say what the function does, not what it is.

Re the context menu plugin: that can be left undocumented as it is indeed a 3rd party library.

Re the Position type: leave it as an `Array.<Number>` for now; when we have more unit tests we can move to an object with enumerated properties.

Re the `canPopOut` function: please promote this to its own issue and assign me.

Apologies again for the delay.

**Comment by daxtens** [comment]
A few private functions in viewobj.js are still undocumented too. It's good to have documentation for them so that anyone developing the object knows what's going on (and so that their types can be checked).

**Comment by daxtens** [comment]
As a final arbitration on `@event`, gjslint doesn't recognise it: `Line 78, E:0200: Invalid JsDoc tag: event`. Also, please run code through gjslint before committing.

**Comment by axtens** [comment]
I just ran the code through gjslint --strict and fixjsstyle --strict. I'm getting this with viewstate.js

```
>gjslint --strict viewstate.js
----- FILE  :  C:\Users\BruceAxtens\Resources\Clients\Daniel\finvis\viewstate.js -----
Line 113, E:0233: Optional parameter name immediate must be prefixed with opt_.
Found 1 errors, including 0 new errors, in 1 files (0 files OK).
```

How does gjslint know it's optional when I don't? And if I put opt_. in front of immediate in the JSDoc markup, then gjslint wants it in the argument list. This is me being ignorant again probably.

**Comment by axtens** [comment]
```
----- FILE  :  C:\Users\BruceAxtens\Resources\Clients\Daniel\finvis\jquery.form.js -----
Line 1094, E:0110: Line too long (138 characters).
Found 1 errors, including 0 new errors, in 1 files (0 files OK).
```

The line at fault is a regular expression. Can regular expressions be split? Offending line is

```
    var re = /^(?:color|date|datetime|email|month|number|password|range|search|tel|text|time|url|week)$/i; // 'hidden' is not in this list
```

**Comment by axtens** [comment]
What should I do about this re this project?

```
warning: push.default is unset; its implicit value is changing in
Git 2.0 from 'matching' to 'simple'. To squelch this message
and maintain the current behavior after the default changes, use:

  git config --global push.default matching

To squelch this message and adopt the new behavior now, use:

  git config --global push.default simple

See 'git help config' and search for 'push.default' for further information.
(the 'simple' mode was introduced in Git 1.7.11. Use the similar mode
'current' instead of 'simple' if you sometimes use older versions of Git)
```

**Comment by axtens** [comment]
What do I do about this lot?

```
----- FILE  :  C:\Users\BruceAxtens\Resources\Clients\Daniel\finvis\viewobj.js -----
Line 23, E:0233: Optional parameter name category must be prefixed with opt_.
Line 649, E:0233: Optional parameter name animate must be prefixed with opt_.
Line 697, E:0233: Optional parameter name aggregate must be prefixed with opt_.
Line 763, E:0233: Optional parameter name animate must be prefixed with opt_.
Line 796, E:0233: Optional parameter name animate must be prefixed with opt_.
Found 5 errors, including 0 new errors, in 1 files (0 files OK).
```

**Comment by daxtens** [comment]
- I haven't been using `--strict`, so I have no idea about those. Any reason I should prefer `---strict`?
- `jquery.*.js` are a jQuery plugins and are 3rd party code, so I haven't been validating them: that's the job of their original authors.
- the git setting is a local issue for you to sort out, rather than a project-wide one: I recommend you switch to simple.

**Comment by axtens** [comment]
- I would have thought that using --strict would take you closer to the other goals faster.
- The original authors aren't on the payroll
- Simple it is

**Comment by daxtens** [comment]
- Perhaps, but now my ability to get sensible data out of `git blame` is lost because everything's been pushed to 2 space indent. A bunch of comments are now broken too: the first line is unindented but the subsequent lines all follow the old 4 space indenting.
- Still don't care: they're 'magical black boxes', and I treat them like binary blobs; I care only about the API they publish.

**Comment by axtens** [comment]
- Oops. My bad. Can reindent to multiples of 4 if you wish.
- Was just up on StackOverflow asking about the weird "opt_" message I was getting in --strict mode: http://stackoverflow.com/questions/15940419/why-optional-parameter-name-s-must-be-prefixed-with-opt-in-gjslint-strict

Is category really optional?

**Comment by daxtens** [comment]
No real point in re-indenting it now.
