### ISSUE TITLE
Sometimes labels 'wobble'

### ISSUE THREAD

**Issue by daxtens** [daxtens/finvis#14]
This is an intermittent, hard to reproduce bug, but sometimes things, especially labels, 'wobble' about and bounce around a bit.

More details to come as I find them.

**Comment by axtens** [comment]
Could some of your x,y values be arriving as something other than integers?

**Comment by daxtens** [comment]
Found it: the zoom handler is running too much: after a drag, it runs at every mouse move. Solve this by only processing the zoom handler when the scale factor actually changes.
