### ISSUE TITLE
Fix private/protected/public methods

### ISSUE THREAD

**Issue by daxtens** [daxtens/finvis#2]
30 mins ($20)

viewobj.js has 2 functions with `// todo: make me private.` or something like that. Find them, and make them private/protected/whatever is appropriate (per [Crockford's article](http://javascript.crockford.com/private.html))

There are some other methods that should obviously be moved: I think _render or something like that. Do the obvious ones in a single commit, if there are any you're not so sure about, do them in a separate commit, or just ask.

If you have time left over, repeat this process with other JS files.

**Comment by axtens** [comment]
//todo: make me private/protected/something

I don't know what you mean by this? Private to what? Protected by what? Sorry, I need clarification of what you're wanting to achieve.

**Comment by daxtens** [comment]
I think I explained that earlier - let me know if you're still stuck.

**Comment by axtens** [comment]
Finished the task ... I think ... and code committed

**Comment by daxtens** [comment]
You need to do a git push.
http://www.kernel.org/pub/software/scm/git/docs/everyday.html#Individual%20Developer%20(Participant)

**Comment by axtens** [comment]
That didn't help me much.
How about you just say "enter the following git command" and show me what it is

**Comment by axtens** [comment]
Hang on. Might have figured it out.

**Comment by axtens** [comment]
No. Going round in circles again.

C:\Users\BruceAxtens\Resources\Clients\Daniel\finvis>git push
Username for 'github.com':
Password for 'github.com':
To https://github.com/daxtens/finvis.git
 ! [rejected]        master -> master (non-fast-forward)
error: failed to push some refs to 'https://github.com/daxtens/finvis.git'
To prevent you from losing history, non-fast-forward updates were rejected
Merge the remote changes (e.g. 'git pull') before pushing again.  See the
'Note about fast-forwards' section of 'git push --help' for details.

C:\Users\BruceAxtens\Resources\Clients\Daniel\finvis>git push --help
Launching default browser to display HTML ...

C:\Users\BruceAxtens\Resources\Clients\Daniel\finvis>cd ..

C:\Users\BruceAxtens\Resources\Clients\Daniel>start .

C:\Users\BruceAxtens\Resources\Clients\Daniel>git push https://github.com/daxtens/finvis.git
fatal: Not a git repository (or any of the parent directories): .git

C:\Users\BruceAxtens\Resources\Clients\Daniel>

If I do a pull, does that overwrite my changes?

**Comment by daxtens** [comment]
No, a git pull won't overwrite, it will do a merge.

**Comment by axtens** [comment]
Okay. I pulled, then pushed and something got pushed

**Comment by axtens** [comment]
By the way, which Python are you using? The versions available to me are at
http://www.activestate.com/activepython/downloads

**Comment by daxtens** [comment]
I have made some comments on the commit.

I am using Python 2.7

**Comment by daxtens** [comment]
Also, please include the issue number (#2) in your commit message. I will update the instructions to reflect this.

**Comment by axtens** [comment]
So is this issue completed, or are you telling me that there's more to do, or that what has been done is not complete?

**Comment by daxtens** [comment]
There's some changes to be made. If you go to the commit, you'll see that there are comments on it. https://github.com/daxtens/finvis/commit/ec5f875d17bc6068fef6e7909a9f851ab9690b0d

**Comment by axtens** [comment]
If I take "this." off line 139 (and turn it into var) or off 169, then the
page fails to arrange the circles appropriately.

**Comment by daxtens** [comment]
OK, remove the line with @private. The rest is good as is.

**Comment by daxtens** [comment]
Yay!
