### ISSUE TITLE
Choose a Unit Test framework?

### ISSUE THREAD

**Issue by daxtens** [daxtens/finvis#4]
I was looking at QUnit. I should pick one and get started.

**Comment by daxtens** [comment]
Consider also http://vowsjs.org

**Comment by axtens** [comment]
http://qunitjs.com/
http://tuttijs.com/
https://github.com/airportyh/testem
http://visionmedia.github.com/mocha/
http://swarm.jquery.org/
http://code.google.com/p/js-test-driver/
https://github.com/atesgoral/jsunity
http://pivotal.github.com/jasmine/

A few more listed on http://stackoverflow.com/questions/300855/looking-for-a-better-javascript-unit-test-tool

**Comment by daxtens** [comment]
Because any decision is better than no decision, QUnit it is.
